---
title: "Data preparation"
output: pdf_document
date: "2024-09-17"
---

```{r}

install.packages("googledrive")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("data.table")
install.packages("jsonlite")
install.packages("strngr")
```

```{r}
library(googledrive)
library(tidyverse)
library(dplyr)
library(data.table)
library(jsonlite)
library(stringr)
```


```{r}

#Acces to the drive without authentication
drive_deauth()

# Folder ID from your Google Drive link
folder_id <- "1ioJVCsr5pJ5tAa2dPJ9yxIvL6rYmDSl1"

# List all files in the folder
files_in_folder <- drive_ls(as_id(folder_id))

# Filter for the file named 'yelp_academic_dataset_business.csv'
csv_file <- files_in_folder[files_in_folder$name == "yelp_academic_dataset_business.csv", ]

# Check if the file exists before attempting download
if (nrow(csv_file) > 0) {
  # Download the CSV file to the working directory
  drive_download(as_id(csv_file$id), path = file.path(getwd(), "yelp_academic_dataset_business.csv"), overwrite = TRUE)
  cat("File downloaded successfully.")
} else {
  cat("The file 'yelp_academic_dataset_business.csv' was not found in the folder.")
}

```

```{r}
business <- read_csv("yelp_academic_dataset_business.csv")

```


```{r exploring the data like class etc. }

# Quick view of the data
head(business$hours)
tail(business)
colnames(business)
summary(business)

```

```{r}

#remove the columns that is not needed for the research

business <- business %>% select(-latitude, -longitude, -hours)

#rearrange the columns in a logical order

business <- business %>% select(business_id, name, is_open ,address, postal_code, city, state, categories, review_count, stars, attributes)

```

```{r}
# Create a dummy variable to see if it is open / yes or no

business$dummy_open <- business$is_open == 1

# We want to delete the rows that have the value FALSE / 0

business <- business %>% filter(business$dummy_open == TRUE)

business$dummy_open <- NULL

```

```{r}
# Find out which columns have NAs
na_count <- colSums(is.na(business))
print(na_count)

# Remove NAs from the necessary columns

business <- business %>%
   filter(!is.na(address) & !is.na(postal_code) & !is.na(attributes))

```

```{r}
# We have to take in consideration when we can say that a review is valid.
# we have to set a banchmark to in our dataset to know what values are valid. 

length(which(business$review_count >= 50))
#output = 23.396

length(which(business$review_count < 50))

#output = 96.302

# Work out the dataset to filter this data

business <- business %>% filter(review_count >= 50)

```


```{r}
## SETUPT
library(readr)
library(data.table)
library(dplyr)
library(tidyr)
library(gridExtra)

## INPUT
cleaned_data <- read_csv('../../data/cleaned_data_for_preperation.csv')
setDT(cleaned_data)

## TRANSFORMATION
# Function to create new dummy variables for category that is put in it
seperate_categories <- function(data, category) {
  # Separating Restaurants
  data <- data %>%
    mutate(dummy_variable = ifelse(grepl(category, data$categories, ignore.case = TRUE), 1, 0)) %>%
    rename(!!paste0("dummy_", category) := dummy_variable) 
  
  return(data)
}

# Function to create frequency table of 1s and 0s per category to check validity of the sample
create_frequency_table <- function(data) {
  # Initialize an empty data frame to store the results
  frequency_table <- data.frame(Variable = character(), Count_0 = integer(), Count_1 = integer(), stringsAsFactors = FALSE)
  
  # Loop through variables 12 to 20
  for (i in 12:20) {
    # Get the counts of 0s and 1s
    count_0 <- sum(data[[i]] == 0, na.rm = TRUE)
    count_1 <- sum(data[[i]] == 1, na.rm = TRUE)
    
    # Append the results to the frequency table
    frequency_table <- rbind(frequency_table, data.frame(Variable = names(data)[i], Count_0 = count_0, Count_1 = count_1))
  }
  
  return(frequency_table)
}

# Specify categories we want to create a dummy variable for
categories <- c("Restaurants", "Shopping", "Home Service", "Beauty & Spas", 
                "Health & Medical", "Local Service", "Automotive", 
                "Active Life", "Hotels & Travel")

# Loop the categories through the separate-categories function and 
for (category in categories) {
  cleaned_data <- seperate_categories(cleaned_data, category)
}
prepared_data <- cleaned_data

# Create frequency table of dummy variables though create_frequency_table
frequency_table_categories = create_frequency_table(prepared_data)
print(frequency_table)

```


```{r}

```

