---
title: "Team Project Dprep"
author: "Team 4"
date: "2024-09-05"
output: pdf_document
---

## Team Project Week 2

This is the deliverable of the dPrep team project of week 2, group 4

```{r}
library(readr)
data_business = read.csv('data/yelp_academic_dataset_business.csv')
summary(data_business)
```
This dataset includes data from the website Yelp on various different businesses. The variables included are the following, with a short elaboration:

* __Business_id__:The unique id of each business
* __Hours__: The opening hours of the business
* __Postal_code__: The postal code of the business
* __Is_open__: If the business is currently open
* __Address__: The address of the business
* __Categories__: The categories the business is classified as
* __Latitude__: The geographical latitude of the business
* __City__: The city the business is located in
* __Longitude__: The geographical longitude of the business
* __State__: The state the business is located in
* __Review_count__: The number of reviews the business had on Yelp
* __Name__: The name of the business
* __Stars__: The star rating of the business on Yelp
* __Attributes__: The attributes of the business

# MOTIVATION
Our team decided to use the dataset from Yelp. After downloading the data, and scanning through it, it was decided that the subset "yelp_academic_dataset_business.csv" was the most interesting to use for our research. 

__Possible research question__ 
Which business attributes lead to a higher star rating? 

We found it to be interesting to see if specific attributes lead to higher ratings for the businesses. For example, if businesses that have “Free Wifi” obtain higher ratings than those that do not present this attribute. We want to study this 

__Research Method__
Regression analysis:

* Converting the attributes into a new dummy variable, indicating whether it is present or not 
* Seeing what effect the presence of these dummies has on the ratings 
* We will use the column "Stars" as well as "Attributes" from the dataset to conduct this analysis. 
* The attributes for a business will be the independent variables (e.g., “Free Wi-Fi,” “Parking,” “Take out”), and the dependent variable would be the business rating (star ranking from 1-5) 
* By using a regression analysis we will be able to quantify the impact of each attribute on the rating.

